apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASS: bd@123
  POSTGRES_DATABASE: projeto_final_asa
  POSTGRES_DRIVERNAME: postgresql+psycopg2
  POSTGRES_PORT: "5432"
